import os
import logging
from typing import List, Dict, Any
import numpy as np
from google import genai
from google.genai import types
from dotenv import load_dotenv

load_dotenv()

logger = logging.getLogger(__name__)

# Initialize Gemini Client
try:
    client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))
except Exception as e:
    logger.error(f"Failed to initialize Gemini Client for grounding: {e}")
    client = None

def get_embedding(text: str) -> List[float]:
    """Generate embedding for a single text."""
    if not client:
        return []
    
    # Use the same model as RAG server
    model = os.getenv("PINECONE_MODEL", "text-embedding-004")
    
    try:
        result = client.models.embed_content(
            model=model,
            contents=text,
            config=types.EmbedContentConfig(
                task_type="RETRIEVAL_QUERY", 
                output_dimensionality=768
            )
        )
        if isinstance(result.embeddings, list):
            return result.embeddings[0].values
        return result.embeddings.values
    except Exception as e:
        logger.error(f"Embedding generation failed: {e}")
        return []

def cosine_similarity(v1: List[float], v2: List[float]) -> float:
    """Calculate cosine similarity between two vectors."""
    if not v1 or not v2:
        return 0.0
    
    vec1 = np.array(v1)
    vec2 = np.array(v2)
    
    norm1 = np.linalg.norm(vec1)
    norm2 = np.linalg.norm(vec2)
    
    if norm1 == 0 or norm2 == 0:
        return 0.0
        
    return float(np.dot(vec1, vec2) / (norm1 * norm2))

def check_grounding(response_text: str, retrieved_context: List[Dict[str, Any]], threshold: float = 0.65) -> Dict[str, Any]:
    """
    Check if the response is grounded in the retrieved context using embedding similarity.
    
    Args:
        response_text: The final response generated by the agent.
        retrieved_context: List of chunks/documents retrieved. Expects dicts with 'content' or 'text' keys.
        threshold: Score below which we consider the response ungrounded.
        
    Returns:
        Dict with 'score' (float), 'supported' (bool), and 'reason' (str).
    """
    if not client:
        return {"score": 0.0, "supported": False, "reason": "Grounding client not initialized"}
        
    if not response_text or not retrieved_context:
        return {"score": 0.0, "supported": False, "reason": "Missing response or context"}

    try:
        # 1. Embed Response
        response_embedding = get_embedding(response_text)
        if not response_embedding:
             return {"score": 0.0, "supported": False, "reason": "Failed to embed response"}

        # 2. Embed Context Chunks
        chunk_texts = []
        for chunk in retrieved_context:
            content = chunk.get('content') or chunk.get('text') or ""
            if content:
                chunk_texts.append(content[:2000])

        if not chunk_texts:
             return {"score": 0.0, "supported": False, "reason": "No valid text in context chunks"}

        # Use the same model as RAG server
        model = os.getenv("PINECONE_MODEL", "text-embedding-004")

        # Batch embedding for context
        try:
            batch_result = client.models.embed_content(
                model=model,
                contents=chunk_texts,
                config=types.EmbedContentConfig(
                    task_type="RETRIEVAL_DOCUMENT",
                    output_dimensionality=768
                )
            )
            # Inspect result structure - assuming list of embeddings
            if batch_result.embeddings:
                 context_embeddings = [e.values for e in batch_result.embeddings]
            else:
                 context_embeddings = []
        except Exception as e:
            logger.warning(f"Batch embedding failed, falling back to sequential: {e}")
            context_embeddings = [get_embedding(t) for t in chunk_texts]

        if not context_embeddings:
            return {"score": 0.0, "supported": False, "reason": "Failed to embed context"}

        # 3. Calculate Max Similarity
        max_score = 0.0
        best_chunk_idx = -1
        
        for i, ctx_emb in enumerate(context_embeddings):
            if not ctx_emb: continue
            score = cosine_similarity(response_embedding, ctx_emb)
            if score > max_score:
                max_score = score
                best_chunk_idx = i
        
        is_supported = max_score >= threshold
        
        logger.info(f"Grounding Check: Score={max_score:.4f}, Threshold={threshold}, Supported={is_supported}")
        
        reason = "Response is supported by context." if is_supported else "Response low similarity to context."
        
        return {
            "score": max_score,
            "supported": is_supported,
            "reason": reason,
            "best_chunk_index": best_chunk_idx
        }

    except Exception as e:
        logger.error(f"Grounding check failed with exception: {e}")
        return {"score": 0.0, "supported": False, "reason": f"Error: {str(e)}"}
